logging:
  path: ./logs

server:
  port: ${PORT:5004}

spring:
  cloud:
    consul:
      discovery:
        tags: traefik.frontend.rule=PathPrefixStrip:/submissions/api
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092,localhost:9093,localhost:9094}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:submissions}
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
